<?php
// Generated by bin/export-wporg-tree.sh — public WordPress.org free edition.
// See Agentic\Distribution.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
if ( ! defined( 'AGENTIC_DIST_CHANNEL' ) ) {
	define( 'AGENTIC_DIST_CHANNEL', 'wporg' );
}
